{% set name = "testtools" %}
{% set version = "2.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/testtools-{{ version }}.tar.gz
  sha256: 5be5bbc1f0fa0f8b60aca6ceec07845d41d0c475cf445bfadb4d2c45ec397ea3

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=61
    - hatchling
    - hatch-vcs
    - wheel
  run:
    - python
  run_constrained:
    - fixtures >=2.0
    - twisted >=22.2

# =======================
# Test configuration
# =======================
{% set test_root = "testtools/tests" %}

# - Skip twisted
# - Skip fixtures
# - Others: assertion/runtime error
{% set skip_files = [
    "testtools/tests/twistedsupport",
    "testtools/tests/matchers",
    "testtools/tests/test_testcase.py",
    "testtools/tests/test_testresult.py",
    "testtools/tests/test_testsuite.py"
] %}

# [win-64]
# with open(path, "rb") as stream:
# PermissionError: [Errno 13] Permission denied: 'C:\\cygwin64\\tmp\\tmpkbmxjt49'
{% set skip_keywords = [
    "test_from_file_with_simple_seek",
    "test_from_file_with_whence_seek"
] %}

test:
  requires:
    - pip
    - pytest
  source_files:
    - {{ test_root }}
  imports:
    - testtools
    - testtools.assertions
    - testtools.compat
    - testtools.content
    - testtools.content_type
    - testtools.helpers
    - testtools.matchers
    - testtools.monkey
    - testtools.runtest
    - testtools.tags
  commands:
    - pip check
    - python -c "import testtools; print(testtools.__version__)"
    - pip install testscenarios
    - pytest -v {{ test_root }}{% for file in skip_files %} --ignore={{ file }}{% endfor %} -k "not ({{ skip_keywords | join(' or ') }})"

about:
  home: https://github.com/testing-cabal/testtools
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Extensions to the Python standard library unit testing framework'
  description: |
    testtools is a set of extensions to the Python standard library's unit testing 
    framework. These extensions have been derived from years of experience 
    with unit testing in Python and come from many different sources.
  dev_url: https://github.com/testing-cabal/testtools
  doc_url: https://testtools.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
  skip-lints:
    - documentation_specifies_language
