{% set name = "testtools" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/testtools-{{ version }}.tar.gz
  sha256: 28b65e14c0f2d3ecbbfb5f55c9dcde5e4faa80ac16a37a823909a1fe3cbcb30a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
    - pbr
  run:
    - python
    - pbr

test:
  imports:
    - testtools
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/testing-cabal/testtools
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Extensions to the Python standard library unit testing framework
  dev_url: https://github.com/testing-cabal/testtools
  doc_url: https://testtools.readthedocs.io

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
