travis:
  secure:
    BINSTAR_TOKEN: jqrUMdbWkH5Knd5pCVKsStcz4wmf5z5WyH60fJbzy4lY+oKY1y8eAd6X2lKsXQ77XB08RPghIHsiZ8ItSBEejuCvvqndQ5Ha0G3oMqDWEOggpaQeoc6Y0YQ2f6AZVMpFiy79F/aktDClZyOcrGDNZL/rYvYEx+NGx7Huk4v1lORS0XWAOWvkh42zv5Nmt1Ckn5cAJ1HUN+4AHdAlwY9YGoPjXOCg9f/7iJF/Tf1BJVVq7NhaNGFwN832n8nKqTmRH0NW3enwhW8uIon+VEg3gc5zdMajpLuSD1E3UacPlvBuSO7c+O/FsNT+sGwuH7D3hjxeuDS+kq4itJY5dm/FfY8xgBOd+yXu91gyNRje7HC2j37G1nXLk2jX04pw8hy7J/Il5+0Q0V5n8zTjV3oaM3lNuohKnupqJgkieiLt+iHRcwhcL9U4YfL7bfgZY4FV6LgZgODcZr9vTbzqQ7ActwIOLb8PVaarPFNsj84lDXhfZJ65SxtbWS/3AudM9RU48krLORmko/U0/ejNzD9v/XMGkW7Nn4mBJ5QK3+xkcTTV4LmSeiuZWFOBtkydnXA2D4zaQz6eKBbEFK2cfp/r6eCHKzxe8DmOWECyhR+oSO5/JytcHPn4DeFi8LulgFWznJQbxvWYWMfhnHocjonPvgNVy6gLck+QU85GkpCHZuI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
