travis:
  secure:
    BINSTAR_TOKEN: m7qVMuuhUcYrARINRAobncznrWTPm7x+oGwbVG8+6PWNoYavk55OUNRaFRREYpDh+cbjYUksJs9kdzqP7fX8j4l8FGc6ZW7qRDajobhL0m2I/901ojZoDgk7gjajsAkXr3pdGIKPuEy86jErV0Xzyrj1xA6qqKkWauljTCiqEXNoKbpoC/xX6PhM0eQyIdWtUzazb6FBkdS/OxX8ZzdjQnUlhbPbGawQp9ECiZDJt61+x/6dyySkARn8YTrpe1zbLcgFF0Ijc2DI1tPb6mj1nwvP+I9Hpx0yIl2neYlmEyGA9I35fpRhIwjb7ZNH9DsUJDfnNmrs9/AlOAbO7E9wHno2wv6TA4nhM5Wg9s/px7U2nNtKUpypPAcStNuv8FCNizOimy5UsbbnkR+lC71X7+e9wtvqdvBuxE3Ii4p9OoevIk7pfKL5RGht/s/5N6IqBE5iQNVypJB7QX0JgyrrrxrLQdUykXsjWN+4j8gPnJPwlcW1Sx5vdffeMALmtT3hagkYvjxda3utnJdfo3tmiAFxIyqRkXL3QUi4kNRMNHbgc/w1BUPFa/7VxOvmFCs0LPNKBBtKVNOheTrUWYV6zE37CnykpJ0edGfBVbXhqwCz7QSu8oKDTRW+CvGaCfylVnwpniXElnsWFzJVNMLr7CR/V0G3lRrOTqTZGsmQKg0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
